package com.tallerplus.interfaz;

import VentanasEmergentes.Mensajes;
import com.tallerplus.gestion.GestionTiempo;
import com.tallerplus.gestion.Login;
import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Clase que gestiona la Ventana Principal, que tiene iconos que te dan acceso a
 * las demás ventanas del programa. Si se presiona el botón de cerrar cierra el
 * programa.
 *
 * @author dani_
 */
public class VentanaPrincipal extends javax.swing.JFrame{

    String tiempo, noticia;
    Desktop enlace=Desktop.getDesktop();

    /**
     * Constructor que inicializa componentes, centra la ventana en la pantalla,
     * la hace visible y evita que sea redimensionable.
     */
    public VentanaPrincipal(){
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        //Cambiamos icono
        ImageIcon ImageIcon=new ImageIcon(getClass().getResource("/com/tallerplus/icon/LogoT+.png"));
        Image Image=ImageIcon.getImage();
        this.setIconImage(Image);

        tiempo=GestionTiempo.pasarTiempo();
        noticia=GestionTiempo.pasarNoticia();
        jtiempo.setText(tiempo);
        jnoticia.setText(noticia);
        jiconotiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/cloudy.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busuario = new javax.swing.JLabel();
        bcliente = new javax.swing.JLabel();
        bfactura = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bhistorialcliente = new javax.swing.JLabel();
        bbuscarcita = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bcitas = new javax.swing.JLabel();
        bcoches = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bcambiousuario = new javax.swing.JLabel();
        jtiempo = new javax.swing.JLabel();
        jiconotiempo = new javax.swing.JLabel();
        jnoticia = new javax.swing.JLabel();
        jicononoticia = new javax.swing.JLabel();

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Buscar Cita");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Buscar Cita");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana principal");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 500));

        panelprincipal.setBackground(new java.awt.Color(109, 132, 180));
        panelprincipal.setMinimumSize(new java.awt.Dimension(900, 500));
        panelprincipal.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("TALLER");
        panelprincipal.add(jLabel1);
        jLabel1.setBounds(21, 266, 99, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ADMINISTRACIÓN");
        panelprincipal.add(jLabel2);
        jLabel2.setBounds(20, 30, 238, 29);

        busuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/social.png"))); // NOI18N
        busuario.setAlignmentY(0.0F);
        busuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                busuarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busuarioMouseEntered(evt);
            }
        });
        panelprincipal.add(busuario);
        busuario.setBounds(60, 100, 128, 128);

        bcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/007-chico.png"))); // NOI18N
        bcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bclienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bclienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bclienteMouseEntered(evt);
            }
        });
        panelprincipal.add(bcliente);
        bcliente.setBounds(280, 100, 128, 128);

        bfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/recepcion.png"))); // NOI18N
        bfactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bfacturaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bfacturaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bfacturaMouseEntered(evt);
            }
        });
        panelprincipal.add(bfactura);
        bfactura.setBounds(500, 100, 118, 128);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Usuarios");
        panelprincipal.add(jLabel6);
        jLabel6.setBounds(60, 70, 69, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Facturas");
        panelprincipal.add(jLabel7);
        jLabel7.setBounds(500, 70, 68, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Clientes");
        panelprincipal.add(jLabel8);
        jLabel8.setBounds(290, 70, 64, 17);

        bhistorialcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/historial.png"))); // NOI18N
        bhistorialcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhistorialcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bhistorialclienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhistorialclienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhistorialclienteMouseEntered(evt);
            }
        });
        panelprincipal.add(bhistorialcliente);
        bhistorialcliente.setBounds(499, 342, 128, 128);

        bbuscarcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/bloc.png"))); // NOI18N
        bbuscarcita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbuscarcita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuscarcitaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbuscarcitaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbuscarcitaMouseEntered(evt);
            }
        });
        panelprincipal.add(bbuscarcita);
        bbuscarcita.setBounds(281, 342, 128, 128);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Añadir Cita");
        panelprincipal.add(jLabel14);
        jLabel14.setBounds(63, 307, 86, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Ver Citas");
        panelprincipal.add(jLabel16);
        jLabel16.setBounds(281, 307, 72, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Historial cliente");
        panelprincipal.add(jLabel20);
        jLabel20.setBounds(499, 307, 122, 17);

        bcitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/calendario.png"))); // NOI18N
        bcitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcitasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcitasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcitasMouseEntered(evt);
            }
        });
        panelprincipal.add(bcitas);
        bcitas.setBounds(63, 342, 128, 128);

        bcoches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/coche.png"))); // NOI18N
        bcoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcoches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcochesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcochesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcochesMouseEntered(evt);
            }
        });
        panelprincipal.add(bcoches);
        bcoches.setBounds(713, 336, 128, 128);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Coches en Venta");
        panelprincipal.add(jLabel9);
        jLabel9.setBounds(713, 307, 135, 17);

        bcambiousuario.setIcon(new javax.swing.ImageIcon("/home/dani/NetBeansProjects/Taller-Plus/src/com/tallerplus/icon/transfer.png")); // NOI18N
        bcambiousuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcambiousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcambiousuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcambiousuarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcambiousuarioMouseEntered(evt);
            }
        });
        panelprincipal.add(bcambiousuario);
        bcambiousuario.setBounds(820, 10, 64, 64);

        jtiempo.setForeground(new java.awt.Color(255, 255, 255));
        jtiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtiempoMouseClicked(evt);
            }
        });
        panelprincipal.add(jtiempo);
        jtiempo.setBounds(680, 20, 122, 29);

        jiconotiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jiconotiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jiconotiempoMouseClicked(evt);
            }
        });
        panelprincipal.add(jiconotiempo);
        jiconotiempo.setBounds(650, 20, 27, 29);

        jnoticia.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jnoticia.setForeground(new java.awt.Color(255, 255, 255));
        jnoticia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jnoticia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnoticiaMouseClicked(evt);
            }
        });
        panelprincipal.add(jnoticia);
        jnoticia.setBounds(310, 20, 310, 29);

        jicononoticia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/text-lines.png"))); // NOI18N
        jicononoticia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jicononoticia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jicononoticiaMouseClicked(evt);
            }
        });
        panelprincipal.add(jicononoticia);
        jicononoticia.setBounds(280, 20, 27, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento al clickar foto "Buscar Cita". Lanza la ventana Buscar Citas.
     *
     * @param evt
     */
    private void bbuscarcitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarcitaMouseClicked
        VerCitas ventanaBuscarCita=new VerCitas();
        dispose();
    }//GEN-LAST:event_bbuscarcitaMouseClicked

    /**
     * Evento al clickar foto "Historial Cliente". Lanza la ventana Historial
     * Cliente.
     *
     * @param evt
     */
    private void bhistorialclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhistorialclienteMouseClicked
        HistorialCliente ventanaHistorialCliente=new HistorialCliente();
        dispose();
    }//GEN-LAST:event_bhistorialclienteMouseClicked
    /**
     * Evento al clickar foto "Usuarios". Lanza la ventana Usuarios.
     *
     * @param evt
     */
    private void busuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busuarioMouseClicked
        if(Login.getUsuarioLogueado().equals("admin")){
            Usuarios ventanaUsuarios=new Usuarios();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No tienes permisos para acceder aquí", "Error", 0);
        }
    }//GEN-LAST:event_busuarioMouseClicked
    /**
     * Evento al clickar foto "Clientes". Lanza la ventana Clientes.
     *
     * @param evt
     */
    private void bclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclienteMouseClicked
        if(!Login.getUsuarioLogueado().equals("mecanico")){
            Clientes ventanaClientes=new Clientes();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No tienes permisos para acceder aquí", "Error", 0);
        }
    }//GEN-LAST:event_bclienteMouseClicked
    /**
     * Evento al clickar foto "Facturas". Lanza la ventana Facturas.
     *
     * @param evt
     */
    private void bfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfacturaMouseClicked
        if(!Login.getUsuarioLogueado().equals("mecanico")){
            Facturas ventanaFacturas=new Facturas();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No tienes permisos para acceder aquí", "Error", 0);
        }
    }//GEN-LAST:event_bfacturaMouseClicked
    /**
     * Evento al clickar foto "Añadir Citas". Lanza la ventana Citas.
     *
     * @param evt
     */
    private void bcitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcitasMouseClicked
        if(!Login.getUsuarioLogueado().equals("mecanico")){
            Citas ventanaCitas=new Citas();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No tienes permisos para acceder aquí", "Error", 0);
        }
    }//GEN-LAST:event_bcitasMouseClicked
    /**
     * Evento al clickar la foto "Coches en venta". Lanza la ventana Ventas.
     *
     * @param evt
     */
    private void bcochesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcochesMouseClicked
        if(!Login.getUsuarioLogueado().equals("mecanico")){
            VentaCoches ventanaVentas=new VentaCoches();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No tienes permisos para acceder aquí", "Error", 0);
        }
    }//GEN-LAST:event_bcochesMouseClicked

    private void busuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busuarioMouseEntered

        busuario.setLocation(busuario.getX(), busuario.getY()+5);
    }//GEN-LAST:event_busuarioMouseEntered

    private void busuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busuarioMouseExited

        busuario.setLocation(busuario.getX(), busuario.getY()-5);
    }//GEN-LAST:event_busuarioMouseExited

    private void bclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclienteMouseEntered

        bcliente.setLocation(bcliente.getX(), bcliente.getY()+5);
    }//GEN-LAST:event_bclienteMouseEntered

    private void bclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclienteMouseExited

        bcliente.setLocation(bcliente.getX(), bcliente.getY()-5);
    }//GEN-LAST:event_bclienteMouseExited

    private void bfacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfacturaMouseEntered

        bfactura.setLocation(bfactura.getX(), bfactura.getY()+5);
    }//GEN-LAST:event_bfacturaMouseEntered

    private void bcitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcitasMouseEntered

        bcitas.setLocation(bcitas.getX(), bcitas.getY()+5);
    }//GEN-LAST:event_bcitasMouseEntered

    private void bcitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcitasMouseExited

        bcitas.setLocation(bcitas.getX(), bcitas.getY()-5);

    }//GEN-LAST:event_bcitasMouseExited

    private void bbuscarcitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarcitaMouseEntered

        bbuscarcita.setLocation(bbuscarcita.getX(), bbuscarcita.getY()+5);
    }//GEN-LAST:event_bbuscarcitaMouseEntered

    private void bhistorialclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhistorialclienteMouseEntered

        bhistorialcliente.setLocation(bhistorialcliente.getX(), bhistorialcliente.getY()+5);
    }//GEN-LAST:event_bhistorialclienteMouseEntered

    private void bbuscarcitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarcitaMouseExited

        bbuscarcita.setLocation(bbuscarcita.getX(), bbuscarcita.getY()-5);
    }//GEN-LAST:event_bbuscarcitaMouseExited

    private void bhistorialclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhistorialclienteMouseExited
        bhistorialcliente.setLocation(bhistorialcliente.getX(), bhistorialcliente.getY()-5);
    }//GEN-LAST:event_bhistorialclienteMouseExited

    private void bcochesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcochesMouseEntered

        bcoches.setLocation(bcoches.getX(), bcoches.getY()+5);
    }//GEN-LAST:event_bcochesMouseEntered

    private void bcochesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcochesMouseExited

        bcoches.setLocation(bcoches.getX(), bcoches.getY()-5);
    }//GEN-LAST:event_bcochesMouseExited

    private void bfacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfacturaMouseExited

        bfactura.setLocation(bfactura.getX(), bfactura.getY()-5);
    }//GEN-LAST:event_bfacturaMouseExited

    private void bcambiousuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcambiousuarioMouseEntered

        bcambiousuario.setLocation(bcambiousuario.getX(), bcambiousuario.getY()+5);
    }//GEN-LAST:event_bcambiousuarioMouseEntered

    private void bcambiousuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcambiousuarioMouseExited

        bcambiousuario.setLocation(bcambiousuario.getX(), bcambiousuario.getY()-5);
    }//GEN-LAST:event_bcambiousuarioMouseExited

    private void bcambiousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcambiousuarioMouseClicked
        LoginUsers login=new LoginUsers();
        dispose();
    }//GEN-LAST:event_bcambiousuarioMouseClicked

    private void jnoticiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnoticiaMouseClicked
        try{
            enlace.browse(new URI("https://www.elespanol.com/ultimas/"));
        }catch(IOException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }catch(URISyntaxException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }
    }//GEN-LAST:event_jnoticiaMouseClicked

    private void jicononoticiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jicononoticiaMouseClicked
        try{
            enlace.browse(new URI("https://www.elespanol.com/ultimas/"));
        }catch(IOException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }catch(URISyntaxException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }
    }//GEN-LAST:event_jicononoticiaMouseClicked

    private void jiconotiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiconotiempoMouseClicked
        try{
            enlace.browse(new URI("https://weather.com/es-ES/tiempo/hoy/l/SPXX0084:1:SP"));
        }catch(IOException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }catch(URISyntaxException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }
    }//GEN-LAST:event_jiconotiempoMouseClicked

    private void jtiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtiempoMouseClicked
        try{
            enlace.browse(new URI("https://weather.com/es-ES/tiempo/hoy/l/SPXX0084:1:SP"));
        }catch(IOException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }catch(URISyntaxException ex){
            Mensajes.ventanaError("Error al abrir la web.", "Error.");
        }
    }//GEN-LAST:event_jtiempoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(InstantiationException ex){
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(IllegalAccessException ex){
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch(javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){

            }
        });
    }

    public void mostrar(){
        setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbuscarcita;
    private javax.swing.JLabel bcambiousuario;
    private javax.swing.JLabel bcitas;
    private javax.swing.JLabel bcliente;
    private javax.swing.JLabel bcoches;
    private javax.swing.JLabel bfactura;
    private javax.swing.JLabel bhistorialcliente;
    private javax.swing.JLabel busuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jicononoticia;
    private javax.swing.JLabel jiconotiempo;
    private javax.swing.JLabel jnoticia;
    private javax.swing.JLabel jtiempo;
    public static javax.swing.JPanel panelprincipal;
    // End of variables declaration//GEN-END:variables
}
